// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HyperionRequest_Command int32

const (
	HyperionRequest_COLOR    HyperionRequest_Command = 1
	HyperionRequest_IMAGE    HyperionRequest_Command = 2
	HyperionRequest_CLEAR    HyperionRequest_Command = 3
	HyperionRequest_CLEARALL HyperionRequest_Command = 4
)

var HyperionRequest_Command_name = map[int32]string{
	1: "COLOR",
	2: "IMAGE",
	3: "CLEAR",
	4: "CLEARALL",
}

var HyperionRequest_Command_value = map[string]int32{
	"COLOR":    1,
	"IMAGE":    2,
	"CLEAR":    3,
	"CLEARALL": 4,
}

func (x HyperionRequest_Command) Enum() *HyperionRequest_Command {
	p := new(HyperionRequest_Command)
	*p = x
	return p
}

func (x HyperionRequest_Command) String() string {
	return proto.EnumName(HyperionRequest_Command_name, int32(x))
}

func (x *HyperionRequest_Command) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HyperionRequest_Command_value, data, "HyperionRequest_Command")
	if err != nil {
		return err
	}
	*x = HyperionRequest_Command(value)
	return nil
}

func (HyperionRequest_Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}

type HyperionReply_Type int32

const (
	HyperionReply_REPLY HyperionReply_Type = 1
	HyperionReply_VIDEO HyperionReply_Type = 2
)

var HyperionReply_Type_name = map[int32]string{
	1: "REPLY",
	2: "VIDEO",
}

var HyperionReply_Type_value = map[string]int32{
	"REPLY": 1,
	"VIDEO": 2,
}

func (x HyperionReply_Type) Enum() *HyperionReply_Type {
	p := new(HyperionReply_Type)
	*p = x
	return p
}

func (x HyperionReply_Type) String() string {
	return proto.EnumName(HyperionReply_Type_name, int32(x))
}

func (x *HyperionReply_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HyperionReply_Type_value, data, "HyperionReply_Type")
	if err != nil {
		return err
	}
	*x = HyperionReply_Type(value)
	return nil
}

func (HyperionReply_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4, 0}
}

type HyperionRequest struct {
	// command specification
	Command                      *HyperionRequest_Command `protobuf:"varint,1,req,name=command,enum=proto.HyperionRequest_Command" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                 `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *HyperionRequest) Reset()         { *m = HyperionRequest{} }
func (m *HyperionRequest) String() string { return proto.CompactTextString(m) }
func (*HyperionRequest) ProtoMessage()    {}
func (*HyperionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

var extRange_HyperionRequest = []proto.ExtensionRange{
	{Start: 10, End: 100},
}

func (*HyperionRequest) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_HyperionRequest
}

func (m *HyperionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HyperionRequest.Unmarshal(m, b)
}
func (m *HyperionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HyperionRequest.Marshal(b, m, deterministic)
}
func (m *HyperionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HyperionRequest.Merge(m, src)
}
func (m *HyperionRequest) XXX_Size() int {
	return xxx_messageInfo_HyperionRequest.Size(m)
}
func (m *HyperionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HyperionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HyperionRequest proto.InternalMessageInfo

func (m *HyperionRequest) GetCommand() HyperionRequest_Command {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return HyperionRequest_COLOR
}

type ColorRequest struct {
	// priority to use when setting the color
	Priority *int32 `protobuf:"varint,1,req,name=priority" json:"priority,omitempty"`
	// integer value containing the rgb color (0x00RRGGBB)
	RgbColor *int32 `protobuf:"varint,2,req,name=RgbColor" json:"RgbColor,omitempty"`
	// duration of the request (negative results in infinite)
	Duration             *int32   `protobuf:"varint,3,opt,name=duration" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ColorRequest) Reset()         { *m = ColorRequest{} }
func (m *ColorRequest) String() string { return proto.CompactTextString(m) }
func (*ColorRequest) ProtoMessage()    {}
func (*ColorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *ColorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColorRequest.Unmarshal(m, b)
}
func (m *ColorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColorRequest.Marshal(b, m, deterministic)
}
func (m *ColorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColorRequest.Merge(m, src)
}
func (m *ColorRequest) XXX_Size() int {
	return xxx_messageInfo_ColorRequest.Size(m)
}
func (m *ColorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ColorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ColorRequest proto.InternalMessageInfo

func (m *ColorRequest) GetPriority() int32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

func (m *ColorRequest) GetRgbColor() int32 {
	if m != nil && m.RgbColor != nil {
		return *m.RgbColor
	}
	return 0
}

func (m *ColorRequest) GetDuration() int32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

var E_ColorRequest_ColorRequest = &proto.ExtensionDesc{
	ExtendedType:  (*HyperionRequest)(nil),
	ExtensionType: (*ColorRequest)(nil),
	Field:         10,
	Name:          "proto.ColorRequest.colorRequest",
	Tag:           "bytes,10,opt,name=colorRequest",
	Filename:      "message.proto",
}

type ImageRequest struct {
	// priority to use when setting the image
	Priority *int32 `protobuf:"varint,1,req,name=priority" json:"priority,omitempty"`
	// width of the image
	Imagewidth *int32 `protobuf:"varint,2,req,name=imagewidth" json:"imagewidth,omitempty"`
	// height of the image
	Imageheight *int32 `protobuf:"varint,3,req,name=imageheight" json:"imageheight,omitempty"`
	// image data
	Imagedata []byte `protobuf:"bytes,4,req,name=imagedata" json:"imagedata,omitempty"`
	// duration of the request (negative results in infinite)
	Duration             *int32   `protobuf:"varint,5,opt,name=duration" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageRequest) Reset()         { *m = ImageRequest{} }
func (m *ImageRequest) String() string { return proto.CompactTextString(m) }
func (*ImageRequest) ProtoMessage()    {}
func (*ImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *ImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageRequest.Unmarshal(m, b)
}
func (m *ImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageRequest.Marshal(b, m, deterministic)
}
func (m *ImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageRequest.Merge(m, src)
}
func (m *ImageRequest) XXX_Size() int {
	return xxx_messageInfo_ImageRequest.Size(m)
}
func (m *ImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImageRequest proto.InternalMessageInfo

func (m *ImageRequest) GetPriority() int32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

func (m *ImageRequest) GetImagewidth() int32 {
	if m != nil && m.Imagewidth != nil {
		return *m.Imagewidth
	}
	return 0
}

func (m *ImageRequest) GetImageheight() int32 {
	if m != nil && m.Imageheight != nil {
		return *m.Imageheight
	}
	return 0
}

func (m *ImageRequest) GetImagedata() []byte {
	if m != nil {
		return m.Imagedata
	}
	return nil
}

func (m *ImageRequest) GetDuration() int32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

var E_ImageRequest_ImageRequest = &proto.ExtensionDesc{
	ExtendedType:  (*HyperionRequest)(nil),
	ExtensionType: (*ImageRequest)(nil),
	Field:         11,
	Name:          "proto.ImageRequest.imageRequest",
	Tag:           "bytes,11,opt,name=imageRequest",
	Filename:      "message.proto",
}

type ClearRequest struct {
	// priority which need to be cleared
	Priority             *int32   `protobuf:"varint,1,req,name=priority" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearRequest) Reset()         { *m = ClearRequest{} }
func (m *ClearRequest) String() string { return proto.CompactTextString(m) }
func (*ClearRequest) ProtoMessage()    {}
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *ClearRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearRequest.Unmarshal(m, b)
}
func (m *ClearRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearRequest.Marshal(b, m, deterministic)
}
func (m *ClearRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearRequest.Merge(m, src)
}
func (m *ClearRequest) XXX_Size() int {
	return xxx_messageInfo_ClearRequest.Size(m)
}
func (m *ClearRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClearRequest proto.InternalMessageInfo

func (m *ClearRequest) GetPriority() int32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

var E_ClearRequest_ClearRequest = &proto.ExtensionDesc{
	ExtendedType:  (*HyperionRequest)(nil),
	ExtensionType: (*ClearRequest)(nil),
	Field:         12,
	Name:          "proto.ClearRequest.clearRequest",
	Tag:           "bytes,12,opt,name=clearRequest",
	Filename:      "message.proto",
}

type HyperionReply struct {
	// Identifies which field is filled in.
	Type *HyperionReply_Type `protobuf:"varint,1,req,name=type,enum=proto.HyperionReply_Type" json:"type,omitempty"`
	// flag indication success or failure
	Success *bool `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
	// string indicating the reason for failure (if applicable)
	Error *string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	// Proto Messages for video mode
	Video                *int32   `protobuf:"varint,4,opt,name=video" json:"video,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HyperionReply) Reset()         { *m = HyperionReply{} }
func (m *HyperionReply) String() string { return proto.CompactTextString(m) }
func (*HyperionReply) ProtoMessage()    {}
func (*HyperionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *HyperionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HyperionReply.Unmarshal(m, b)
}
func (m *HyperionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HyperionReply.Marshal(b, m, deterministic)
}
func (m *HyperionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HyperionReply.Merge(m, src)
}
func (m *HyperionReply) XXX_Size() int {
	return xxx_messageInfo_HyperionReply.Size(m)
}
func (m *HyperionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HyperionReply.DiscardUnknown(m)
}

var xxx_messageInfo_HyperionReply proto.InternalMessageInfo

func (m *HyperionReply) GetType() HyperionReply_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return HyperionReply_REPLY
}

func (m *HyperionReply) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *HyperionReply) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *HyperionReply) GetVideo() int32 {
	if m != nil && m.Video != nil {
		return *m.Video
	}
	return 0
}

func init() {
	proto.RegisterEnum("proto.HyperionRequest_Command", HyperionRequest_Command_name, HyperionRequest_Command_value)
	proto.RegisterEnum("proto.HyperionReply_Type", HyperionReply_Type_name, HyperionReply_Type_value)
	proto.RegisterType((*HyperionRequest)(nil), "proto.HyperionRequest")
	proto.RegisterExtension(E_ColorRequest_ColorRequest)
	proto.RegisterType((*ColorRequest)(nil), "proto.ColorRequest")
	proto.RegisterExtension(E_ImageRequest_ImageRequest)
	proto.RegisterType((*ImageRequest)(nil), "proto.ImageRequest")
	proto.RegisterExtension(E_ClearRequest_ClearRequest)
	proto.RegisterType((*ClearRequest)(nil), "proto.ClearRequest")
	proto.RegisterType((*HyperionReply)(nil), "proto.HyperionReply")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x65, 0xd2, 0x84, 0xb6, 0xb7, 0x79, 0x1a, 0x46, 0x91, 0x51, 0x1e, 0x8f, 0x90, 0x55, 0x11,
	0xec, 0xa2, 0xab, 0xb7, 0x2d, 0x35, 0x68, 0x21, 0x12, 0x19, 0x44, 0x70, 0x19, 0x93, 0x21, 0x1d,
	0x48, 0x3a, 0x71, 0x32, 0x55, 0x82, 0x9f, 0xe0, 0x5f, 0xf8, 0x0b, 0x7e, 0x9c, 0x5b, 0x99, 0x49,
	0xe2, 0x9b, 0xf8, 0x7c, 0xd0, 0x55, 0xe6, 0x9c, 0x7b, 0xe6, 0xce, 0x39, 0x37, 0x17, 0xae, 0x6a,
	0xd6, 0xb6, 0x59, 0xc9, 0x36, 0x8d, 0x14, 0x4a, 0x60, 0xcf, 0x7c, 0xa2, 0x1f, 0x08, 0x1e, 0xbf,
	0xed, 0x1a, 0x26, 0xb9, 0x38, 0x51, 0xf6, 0xe5, 0xcc, 0x5a, 0x85, 0x6f, 0x61, 0x9e, 0x8b, 0xba,
	0xce, 0x4e, 0x05, 0x41, 0xa1, 0xb3, 0x7e, 0xb4, 0xbd, 0xe9, 0xef, 0x6c, 0xfe, 0x11, 0x6e, 0xf6,
	0xbd, 0x8a, 0x8e, 0xf2, 0xe8, 0x16, 0xe6, 0x03, 0x87, 0x97, 0xe0, 0xed, 0xd3, 0x24, 0xa5, 0x01,
	0xd2, 0xc7, 0xc3, 0xbb, 0xdd, 0x9b, 0x38, 0x70, 0x0c, 0x9b, 0xc4, 0x3b, 0x1a, 0xcc, 0xb0, 0x0f,
	0x0b, 0x73, 0xdc, 0x25, 0x49, 0xe0, 0xbe, 0x74, 0x17, 0x10, 0xb0, 0xe8, 0x17, 0x02, 0x7f, 0x2f,
	0x2a, 0x21, 0x47, 0x2b, 0x2f, 0x60, 0xd1, 0x48, 0x2e, 0x24, 0x57, 0x9d, 0xf1, 0xe2, 0xd1, 0xbf,
	0x58, 0xd7, 0x68, 0xf9, 0xd9, 0xc8, 0x89, 0xd3, 0xd7, 0x46, 0xac, 0x6b, 0xc5, 0x59, 0x66, 0x8a,
	0x8b, 0x13, 0x99, 0x85, 0x48, 0xd7, 0x46, 0xbc, 0x4d, 0xc1, 0xcf, 0xed, 0x37, 0x9e, 0xfd, 0x3f,
	0x1d, 0x81, 0x10, 0xad, 0x57, 0xdb, 0x27, 0x43, 0xd5, 0xb6, 0x45, 0x27, 0x0d, 0xa2, 0xdf, 0x08,
	0xfc, 0x43, 0x9d, 0x95, 0xec, 0x12, 0xd7, 0x37, 0x00, 0x5c, 0x6b, 0xbf, 0xf1, 0x42, 0x1d, 0x07,
	0xdf, 0x16, 0x83, 0x43, 0x58, 0x19, 0x74, 0x64, 0xbc, 0x3c, 0x2a, 0x32, 0x33, 0x02, 0x9b, 0xc2,
	0xd7, 0xb0, 0x34, 0xb0, 0xc8, 0x54, 0x46, 0xdc, 0xd0, 0x59, 0xfb, 0xf4, 0x8e, 0x98, 0x24, 0xf7,
	0xee, 0x27, 0xe7, 0xb6, 0xcf, 0x87, 0x92, 0xaf, 0x26, 0xc9, 0xed, 0x68, 0x74, 0xd2, 0x20, 0xfa,
	0x0e, 0xfe, 0xbe, 0x62, 0xd9, 0x25, 0xbf, 0xcb, 0x8c, 0xdd, 0xd6, 0x3e, 0xf4, 0xb8, 0x3f, 0x1d,
	0xbb, 0x75, 0x85, 0x4e, 0x1a, 0x44, 0x3f, 0x11, 0x5c, 0xdd, 0x5d, 0x6e, 0xaa, 0x0e, 0xbf, 0x02,
	0x57, 0x75, 0x0d, 0x1b, 0xb6, 0xf6, 0xf9, 0xbd, 0x07, 0x9a, 0xaa, 0xdb, 0x7c, 0xe8, 0x1a, 0x46,
	0x8d, 0x0c, 0x13, 0x98, 0xb7, 0xe7, 0x3c, 0x67, 0x6d, 0x4b, 0x9c, 0x10, 0xad, 0x17, 0x74, 0x84,
	0xf8, 0x29, 0x78, 0x4c, 0x4a, 0x21, 0xcd, 0xee, 0x2c, 0x69, 0x0f, 0x34, 0xfb, 0x95, 0x17, 0x4c,
	0x10, 0xd7, 0xcc, 0xb5, 0x07, 0xd1, 0x35, 0xb8, 0xba, 0xa7, 0x5e, 0x6d, 0x1a, 0xbf, 0x4f, 0x3e,
	0xf5, 0x0b, 0xff, 0xf1, 0xf0, 0x3a, 0x4e, 0x03, 0xe7, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x80,
	0xd2, 0x1e, 0xaf, 0x76, 0x03, 0x00, 0x00,
}
